included:
  - ProjectManager

excluded:
  - Pods
  - ProjectManager/AppDelegate.swift
  - ProjectManager/SceneDelegate.swift
   
disabled_rules:
  - colon
  - control_statement
  - trailing_whitespace
  - vertical_parameter_alignment

opt_in_rules:
  - empty_count
  - conditional_returns_on_newline
