
excluded:
  - ProjectManager/AppDelegate.swift
  - ProjectManager/SceneDelegate.swift
  - ProjectManager/Presentation/Main/View/MainViewController.swift

#function_body_length:
#    warning: 10
#    error: 15
type_body_length:
    warning: 200
    error: 250

disabled_rules:
  - identifier_name
