excluded:
    - Pods

included:
    - ProjectManager

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - closure_spacing
  - implicitly_unwrapped_optional
  - vertical_whitespace_closing_braces
  
disabled_rules:
  - trailing_whitespace
  - class_delegate_protocol

line_length: 100
