included: # 린트 과정에 포함할 파일 경로. 이 항목이 존재하면 --path는 무시됨
  - ProjectManager

excluded: # 린트 과정에서 무시할 파일 경로. included보다 우선순위 높음
  - ProjectManager/AppLifecycle/AppDelegate.swift
  - ProjectManager/AppLifecycle/SceneDelegate.swift

disabled_rules: # 실행에서 제외할 룰 식별자들
  - trailing_whitespace

identifier_name:
  min_length:
    error: 2
  excluded:
    - to
