excluded:
- Pods
- Diary/AppDelegate.swift
- Diary/SceneDelegate.swift

disabled_rules:
- trailing_whitespace
- line_length
- force_cast
- unused_closure_parameter
- vertical_parameter_alignment
- unused_optional_binding
