
excluded:
- ProjectManager/AppDelegate.swift
- ProjectManager/SceneDelegate.swift

disabled_rules:
- trailing_whitespace
- identifier_name
- force_cast
- force_try
- type_body_length
- file_length
- type_name
- line_length
- cyclomatic_complexity
- nesting
- duplicate_imports
- syntactic_sugar
- trailing_comma
- todo
- vertical_whitespace
- function_body_length
- block_based_kvo
