disabled_rules:
 - line_length
 - trailing_whitespace

included:
 - ProjectManager

opt_in_rules:
 - force_unwrapping
 - empty_count

excluded:
 - Pods
 - ProjectManager/AppDelegate.swift
 - ProjectManager/SceneDelegate.swift

