# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectManager
 pod 'SwiftLint'
  target 'ProjectManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectManagerUITests' do
    # Pods for testing
  end

end
