# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectManager
  pod 'SwiftLint'
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'
  pod 'RxRelay', '~> 6.5.0'
  pod 'RxDataSources'
  pod 'RxGesture'
  pod 'FirebaseDatabase'
  pod 'ReachabilitySwift'
  
  target 'ProjectManagerTests' do
    inherit! :search_paths
  end
end
