disabled_rules:
    - trailing_whitespace
    - force_cast
    - force_unwrapping
opt_in_rules:
  - empty_count
  - empty_string
  
line_length:
  warning: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
